version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: shampay-api
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: shampay-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: shampay

volumes:
  mongo-data:
